// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13.11.2025, 00:08:08
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/user/Documents/vscode/himmed-tech/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Documents/vscode/himmed-tech/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Documents/vscode/himmed-tech/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Documents/vscode/himmed-tech/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Documents/vscode/himmed-tech/plugins/**/*.{js,ts,mjs}","C:/Users/user/Documents/vscode/himmed-tech/composables/**/*.{js,ts,mjs}","C:/Users/user/Documents/vscode/himmed-tech/utils/**/*.{js,ts,mjs}","C:/Users/user/Documents/vscode/himmed-tech/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Documents/vscode/himmed-tech/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Documents/vscode/himmed-tech/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Documents/vscode/himmed-tech/app.config.{js,ts,mjs}","C:/Users/user/Documents/vscode/himmed-tech/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;